import { z } from 'zod';

export const contactSchema = z.object({
  nature: z.string().min(1, 'Nature is required'),
  contact_type: z.number().min(1, 'Contact type is required'),
  prefix: z.string().min(1, 'Prefix is required'),
  first_name: z.string().min(1, 'First name is required'),
  middle_name: z.string().min(1, 'Middle name is required'),
  last_name: z.string().min(1, 'Last name is required'),
  suffix: z.string().min(1, 'Suffix is required'),
  gender: z.string().min(1, 'Gender is required'),
  alias: z.string().min(1, 'Alias is required'),
  marital_status: z.string().min(1, 'Marital status is required'),
  company_name: z.string().min(1, 'Company name is required'),
  job_title: z.string().min(1, 'Job title is required'),
  ssn: z.string().min(1, 'SSN is required'),
  federal_tax_id: z.string().min(1, 'Federal tax ID is required'),
  work_phone: z.string().min(1, 'Work phone is required'),
  home_phone: z.string().min(1, 'Home phone is required'),
  primary_phone: z.string().min(1, 'Primary phone is required'),
  fax: z.string().min(1, 'Fax is required'),
  primary_email: z.string().email('Primary email is required'),
  secondary_email: z.string().email('Secondary email is required'),
  when_to_contact: z.string().min(1, 'When to contact is required'),
  contact_preference: z.string().min(1, 'Contact preference is required'),
  language: z.string().min(1, 'Language is required'),
  drivers_license: z.string().min(1, 'Drivers license is required'),
  date_of_birth: z.string().min(1, 'Date of birth is required'),
  date_of_death: z.string().min(1, 'Date of death is required'),
  date_of_bankruptcy: z.string().min(1, 'Date of bankruptcy is required'),
  notes: z.string().min(1, 'Notes is required'),
  firm_id: z.string().min(1, 'Firm ID is required'),
  created_by: z.string().min(1, 'Created by is required'),
  addresses: z.array(
    z.object({
      address_1: z.string().min(1, 'Address 1 is required'),
      address_2: z.string().min(1, 'Address 2 is required'),
      city: z.string().min(1, 'City is required'),
      county: z.string().min(1, 'County is required'),
      state: z.string().min(1, 'State is required'),
      zip: z.string().min(1, 'Zip is required'),
      country: z.string().min(1, 'Country is required'),
      is_primary: z.boolean(),
      address_type: z.string().min(1, 'Address type is required'),
    })
  ),
});
